require 'plugins.fugitive'
require 'plugins.custom-manim'
require 'plugins.fzf-lua'
require 'plugins.lualine'
require 'plugins.tokyonight'
require 'plugins.treesitter'
require 'plugins.undotree'
require 'plugins.vimtex'
